version: '3'

volumes:
  rabbitmq_data: {}
  rabbitmq_logs: {}

networks:
  rabbitmq: 

services:
  api:
    build:
      context: .
    ports:
      - '10000:10000'
    networks:
        - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_logs:/var/log/rabbitmq
    networks:
        - rabbitmq
