apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  annotations:
    kubernetes.io/service-account.name: "cluster-autoscaler"
type: kubernetes.io/service-account-token
data:
  token: $HCLOUD_TOKEN
