- name: Check if kubeadm has already running
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: If cluter not running join
  include_tasks: join.yml
  when: not kubeadm_ca.stat.exists
  register: join_complete
