apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-deployment
  labels:
    app: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels: 
        app: metrics
    spec:
      containers:
        - name: metrics
          image: ghcr.io/jelgar/auto-q8s/metrics:main
          imagePullPolicy: Always
          env:
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  name: queue-default-user
                  key: username
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: queue-default-user
                  key: password
            - name: RMQ_HOST
              value: "queue"
            - name: RMQ_PORT
              value: "5672"
            - name: AWS_ACCESS_KEY_ID
              value: "$AWS_ACCESS_KEY_ID"
            - name: AWS_SECRET_ACCESS_KEY 
              value: "$AWS_SECRET_ACCESS_KEY"
            - name: DYNAMO_TABLE
              value: "$DYNAMO_TABLE"
            - name: HCLOUD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hcloud 
                  key: token 
