apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: producer-cert
  namespace: istio-system
spec:
  secretName: producer-cert
  commonName: producer.$CLUSTER_BASE_URL
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - producer.$CLUSTER_BASE_URL
