apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels: 
        app: producer
    spec:
      containers:
        - name:  
          image: nginx:latest
          ports:
            - containerPort: 80
