apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: queue 
spec:
  persistence:
    storageClassName: "local-path"
    storage: 50Mi
  service:
    type: ClusterIP 
  replicas: 1
