---

- name: Check if kubeadm has already running
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: If cluter not running init 
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes
