version: '3'

volumes:
  rabbitmq_data: {}
  rabbitmq_logs: {}

networks:
  rabbitmq: 

services:
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - rabbitmq
    environment:
      - RMQ_USER=guest
      - RMQ_PASSWORD=guest
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
    depends_on:
      - rabbitmq
  
  consumer:
    build:
      context: .
      dockerfile: consumer/Dockerfile
    env_file:
      - ../.env
    networks:
      - rabbitmq
    environment:
      - RMQ_USER=guest
      - RMQ_PASSWORD=guest
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - DYNAMO_TABLE=outputs-82168b4
    depends_on:
      - rabbitmq
  
  metrics:
    build:
      context: .
      dockerfile: metrics/Dockerfile
    env_file:
      - ../.env
    networks:
      - rabbitmq
    environment:
      - RMQ_USER=guest
      - RMQ_PASSWORD=guest
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - DYNAMO_TABLE=outputs-82168b4
    depends_on:
      - rabbitmq
  
  scaler:
    build:
      context: .
      dockerfile: scaler/Dockerfile
    networks:
      - rabbitmq
    env_file:
      - ../.env
    environment:
      - RMQ_USER=guest
      - RMQ_PASSWORD=guest
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
    depends_on:
      - rabbitmq
    volumes:
      - ~/.ssh/id_rsa:/etc/ssh-key/private-key:ro

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_logs:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
        - rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
