- name: Provision master node
  hosts: master_init_node
  become: yes
  become_user: root
  roles:
    - setup
    - master_init
    
- name: Export join command 
  hosts: localhost 
  become: no 
  roles:
    - role: export_join 

- name: Join other master node
  hosts: master_join_nodes
  become: yes
  become_user: root
  roles:
    - role: setup 
    - role: master_join
      
- name: Join worker node
  hosts: worker_nodes
  become: yes
  become_user: root
  roles:
    - role: setup 
    - role: worker_join
