name: Docker build and push

on:
  push:
    branches: [ main ]
    paths:
    - 'apps/**'

    
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v2
        
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Extract metadata (tags, labels) for consumer
      id: consumer-meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/consumer
        
    - name: Extract metadata (tags, labels) for producer
      id: producer-meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/producer

    - name: Extract metadata (tags, labels) for scaler 
      id: scaler-meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}/scaler
        
    - name: Build and push consumer docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: apps 
        file: apps/consumer/Dockerfile
        tags: ${{ steps.consumer-meta.outputs.tags }}
        labels: ${{ steps.consumer-meta.outputs.labels }}
        push: true
        
    - name: Build and push producer docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: apps 
        file: apps/producer/Dockerfile
        tags: ${{ steps.producer-meta.outputs.tags }}
        labels: ${{ steps.producer-meta.outputs.labels }}
        push: true
    
    - name: Build and push scaler docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: apps 
        file: apps/scaler/Dockerfile
        tags: ${{ steps.scaler-meta.outputs.tags }}
        labels: ${{ steps.scaler-meta.outputs.labels }}
        push: true


